repos:
  # BLACK
  - hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=80
    repo: https://github.com/psf/black
    rev: 22.3.0
  # DOCFORMATTER
  - hooks:
      - id: docformatter
        args:
          - -i
          - -r
          - --pre-summary-newline
          - --make-summary-multi-line
    repo: https://github.com/myint/docformatter
    rev: 'v1.4'
  # ISORT
  # - hooks:
  #     - id: isort
  #       args:
  #         - --profile=black
  #         - --line-length=80
  #   repo: https://github.com/pycqa/isort
  #   rev: '5.7.0'
  # LOCAL HOOKS
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: .venv/bin/mypy
        args:
          - --config-file=mypy.ini
        exclude: tests
        types:
          - python
        files: py9lib
      # pytest
      - id: pytest
        name: pytest
        language: system
        entry: /usr/bin/pytest
        args:
          - tests
        pass_filenames: false
        types:
          - python